name = "hologram-store-holiday-api"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-03-22"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
